# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sales_status',
            field=models.CharField(blank=True, default='In Stock', max_length=25, null=True),
        ),
    ]
