# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billit', '0002_auto_20170115_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sold_by',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
