# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billit', '0004_auto_20170117_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cust_Email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='cust_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='cust_phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sold_price',
            field=models.IntegerField(null=True),
        ),
    ]
