# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billit', '0005_auto_20170117_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sales_date',
            field=models.DateField(auto_now=True),
        ),
    ]
