# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billit', '0008_auto_20170117_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='prod_img',
            field=models.ImageField(blank=True, height_field='100', null=True, upload_to='', width_field='75'),
        ),
    ]
